# Generated by Django 5.1.2 on 2024-10-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='имя')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('photo', models.ImageField(upload_to='', verbose_name='фото')),
            ],
        ),
    ]
